# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.infrastructure.clients.menu_grpc import menu_pb2 as menu__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in menu_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MenuServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMenuItem = channel.unary_unary(
                '/MenuService/CreateMenuItem',
                request_serializer=menu__pb2.CreateMenuItemRequest.SerializeToString,
                response_deserializer=menu__pb2.MenuItemResponse.FromString,
                _registered_method=True)
        self.GetMenuItem = channel.unary_unary(
                '/MenuService/GetMenuItem',
                request_serializer=menu__pb2.GetMenuItemRequest.SerializeToString,
                response_deserializer=menu__pb2.MenuItemResponse.FromString,
                _registered_method=True)
        self.ListMenuItems = channel.unary_unary(
                '/MenuService/ListMenuItems',
                request_serializer=menu__pb2.ListMenuItemsRequest.SerializeToString,
                response_deserializer=menu__pb2.ListMenuItemsResponse.FromString,
                _registered_method=True)
        self.UpdateMenuItem = channel.unary_unary(
                '/MenuService/UpdateMenuItem',
                request_serializer=menu__pb2.UpdateMenuItemRequest.SerializeToString,
                response_deserializer=menu__pb2.MenuItemResponse.FromString,
                _registered_method=True)
        self.DeleteMenuItem = channel.unary_unary(
                '/MenuService/DeleteMenuItem',
                request_serializer=menu__pb2.DeleteMenuItemRequest.SerializeToString,
                response_deserializer=menu__pb2.DeleteMenuItemResponse.FromString,
                _registered_method=True)
        self.RestoreMenuItem = channel.unary_unary(
                '/MenuService/RestoreMenuItem',
                request_serializer=menu__pb2.RestoreMenuItemRequest.SerializeToString,
                response_deserializer=menu__pb2.MenuItemResponse.FromString,
                _registered_method=True)


class MenuServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateMenuItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMenuItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMenuItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMenuItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMenuItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreMenuItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MenuServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateMenuItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMenuItem,
                    request_deserializer=menu__pb2.CreateMenuItemRequest.FromString,
                    response_serializer=menu__pb2.MenuItemResponse.SerializeToString,
            ),
            'GetMenuItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMenuItem,
                    request_deserializer=menu__pb2.GetMenuItemRequest.FromString,
                    response_serializer=menu__pb2.MenuItemResponse.SerializeToString,
            ),
            'ListMenuItems': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMenuItems,
                    request_deserializer=menu__pb2.ListMenuItemsRequest.FromString,
                    response_serializer=menu__pb2.ListMenuItemsResponse.SerializeToString,
            ),
            'UpdateMenuItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMenuItem,
                    request_deserializer=menu__pb2.UpdateMenuItemRequest.FromString,
                    response_serializer=menu__pb2.MenuItemResponse.SerializeToString,
            ),
            'DeleteMenuItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMenuItem,
                    request_deserializer=menu__pb2.DeleteMenuItemRequest.FromString,
                    response_serializer=menu__pb2.DeleteMenuItemResponse.SerializeToString,
            ),
            'RestoreMenuItem': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreMenuItem,
                    request_deserializer=menu__pb2.RestoreMenuItemRequest.FromString,
                    response_serializer=menu__pb2.MenuItemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MenuService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MenuService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MenuService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateMenuItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MenuService/CreateMenuItem',
            menu__pb2.CreateMenuItemRequest.SerializeToString,
            menu__pb2.MenuItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMenuItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MenuService/GetMenuItem',
            menu__pb2.GetMenuItemRequest.SerializeToString,
            menu__pb2.MenuItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMenuItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MenuService/ListMenuItems',
            menu__pb2.ListMenuItemsRequest.SerializeToString,
            menu__pb2.ListMenuItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMenuItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MenuService/UpdateMenuItem',
            menu__pb2.UpdateMenuItemRequest.SerializeToString,
            menu__pb2.MenuItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMenuItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MenuService/DeleteMenuItem',
            menu__pb2.DeleteMenuItemRequest.SerializeToString,
            menu__pb2.DeleteMenuItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreMenuItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MenuService/RestoreMenuItem',
            menu__pb2.RestoreMenuItemRequest.SerializeToString,
            menu__pb2.MenuItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
