"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _MenuCategory:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MenuCategoryEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MenuCategory.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    APPETIZER: _MenuCategory.ValueType  # 0
    MAIN_COURSE: _MenuCategory.ValueType  # 1
    DESSERT: _MenuCategory.ValueType  # 2
    SOFT_DRINK: _MenuCategory.ValueType  # 3
    JUICE: _MenuCategory.ValueType  # 4
    ALCOHOLIC_BEVERAGE: _MenuCategory.ValueType  # 5
    OTHER: _MenuCategory.ValueType  # 6

class MenuCategory(_MenuCategory, metaclass=_MenuCategoryEnumTypeWrapper): ...

APPETIZER: MenuCategory.ValueType  # 0
MAIN_COURSE: MenuCategory.ValueType  # 1
DESSERT: MenuCategory.ValueType  # 2
SOFT_DRINK: MenuCategory.ValueType  # 3
JUICE: MenuCategory.ValueType  # 4
ALCOHOLIC_BEVERAGE: MenuCategory.ValueType  # 5
OTHER: MenuCategory.ValueType  # 6
global___MenuCategory = MenuCategory

@typing.final
class Empty(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Empty = Empty

@typing.final
class MenuItem(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    CATEGORY_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    AVAILABLE_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    id: builtins.int
    name: builtins.str
    category: global___MenuCategory.ValueType
    price: builtins.float
    available: builtins.bool
    description: builtins.str
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        name: builtins.str = ...,
        category: global___MenuCategory.ValueType = ...,
        price: builtins.float = ...,
        available: builtins.bool = ...,
        description: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["available", b"available", "category", b"category", "description", b"description", "id", b"id", "name", b"name", "price", b"price"]) -> None: ...

global___MenuItem = MenuItem

@typing.final
class CreateMenuItemRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    CATEGORY_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    AVAILABLE_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    name: builtins.str
    category: global___MenuCategory.ValueType
    price: builtins.float
    available: builtins.bool
    description: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        category: global___MenuCategory.ValueType = ...,
        price: builtins.float = ...,
        available: builtins.bool = ...,
        description: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["available", b"available", "category", b"category", "description", b"description", "name", b"name", "price", b"price"]) -> None: ...

global___CreateMenuItemRequest = CreateMenuItemRequest

@typing.final
class GetMenuItemRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___GetMenuItemRequest = GetMenuItemRequest

@typing.final
class ListMenuItemsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CATEGORY_FIELD_NUMBER: builtins.int
    MIN_PRICE_FIELD_NUMBER: builtins.int
    MAX_PRICE_FIELD_NUMBER: builtins.int
    AVAILABLE_FIELD_NUMBER: builtins.int
    SEARCH_QUERY_FIELD_NUMBER: builtins.int
    category: global___MenuCategory.ValueType
    min_price: builtins.float
    max_price: builtins.float
    available: builtins.bool
    search_query: builtins.str
    def __init__(
        self,
        *,
        category: global___MenuCategory.ValueType | None = ...,
        min_price: builtins.float | None = ...,
        max_price: builtins.float | None = ...,
        available: builtins.bool | None = ...,
        search_query: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_available", b"_available", "_category", b"_category", "_max_price", b"_max_price", "_min_price", b"_min_price", "_search_query", b"_search_query", "available", b"available", "category", b"category", "max_price", b"max_price", "min_price", b"min_price", "search_query", b"search_query"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_available", b"_available", "_category", b"_category", "_max_price", b"_max_price", "_min_price", b"_min_price", "_search_query", b"_search_query", "available", b"available", "category", b"category", "max_price", b"max_price", "min_price", b"min_price", "search_query", b"search_query"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_available", b"_available"]) -> typing.Literal["available"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_category", b"_category"]) -> typing.Literal["category"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_max_price", b"_max_price"]) -> typing.Literal["max_price"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_min_price", b"_min_price"]) -> typing.Literal["min_price"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_search_query", b"_search_query"]) -> typing.Literal["search_query"] | None: ...

global___ListMenuItemsRequest = ListMenuItemsRequest

@typing.final
class UpdateMenuItemRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    CATEGORY_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    AVAILABLE_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    id: builtins.int
    name: builtins.str
    category: global___MenuCategory.ValueType
    price: builtins.float
    available: builtins.bool
    description: builtins.str
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        name: builtins.str | None = ...,
        category: global___MenuCategory.ValueType | None = ...,
        price: builtins.float | None = ...,
        available: builtins.bool | None = ...,
        description: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_available", b"_available", "_category", b"_category", "_description", b"_description", "_name", b"_name", "_price", b"_price", "available", b"available", "category", b"category", "description", b"description", "name", b"name", "price", b"price"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_available", b"_available", "_category", b"_category", "_description", b"_description", "_name", b"_name", "_price", b"_price", "available", b"available", "category", b"category", "description", b"description", "id", b"id", "name", b"name", "price", b"price"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_available", b"_available"]) -> typing.Literal["available"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_category", b"_category"]) -> typing.Literal["category"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_description", b"_description"]) -> typing.Literal["description"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_name", b"_name"]) -> typing.Literal["name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_price", b"_price"]) -> typing.Literal["price"] | None: ...

global___UpdateMenuItemRequest = UpdateMenuItemRequest

@typing.final
class DeleteMenuItemRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    PERMANENT_FIELD_NUMBER: builtins.int
    id: builtins.int
    permanent: builtins.bool
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        permanent: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "permanent", b"permanent"]) -> None: ...

global___DeleteMenuItemRequest = DeleteMenuItemRequest

@typing.final
class RestoreMenuItemRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___RestoreMenuItemRequest = RestoreMenuItemRequest

@typing.final
class MenuItemResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ITEM_FIELD_NUMBER: builtins.int
    @property
    def item(self) -> global___MenuItem: ...
    def __init__(
        self,
        *,
        item: global___MenuItem | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["item", b"item"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["item", b"item"]) -> None: ...

global___MenuItemResponse = MenuItemResponse

@typing.final
class ListMenuItemsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ITEMS_FIELD_NUMBER: builtins.int
    @property
    def items(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MenuItem]: ...
    def __init__(
        self,
        *,
        items: collections.abc.Iterable[global___MenuItem] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["items", b"items"]) -> None: ...

global___ListMenuItemsResponse = ListMenuItemsResponse

@typing.final
class DeleteMenuItemResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    IS_SOFT_DELETED_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    is_soft_deleted: builtins.bool
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
        is_soft_deleted: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["is_soft_deleted", b"is_soft_deleted", "message", b"message", "success", b"success"]) -> None: ...

global___DeleteMenuItemResponse = DeleteMenuItemResponse
