services:
  order-services:
    container_name: dev-order-services
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "8081:8081"
    env_file:
      - .env.dev
    networks:
      - core-infrastructure-dev

networks:
  core-infrastructure-dev:
    external: true
