apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: postgresql+asyncpg://postgres:password@host.minikube.internal:5432/db
            - name: DJANGO_SERVICE_URL
              value: http://host.minikube.internal:8000
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10

