apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-services
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-services
  template:
    metadata:
      labels:
        app: order-services
    spec:
      containers:
        - name: order-services
          image: order-services:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: order-services-config
